# ./dev/docker-compose.yml (Base configuration)
services:
  app:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - ENVIRONMENT=production

